---
- name: Ensure dependency is installed (Ubuntu)
  apt: 
    name: apt-transport-https
  when: ansible_os_family == 'Debian'

- name: Add Elasticsearch apt key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
  when: ansible_os_family == 'Debian'

- name: Add Kibana repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Kibana
  package: 
    name: kibana

- name: Ensure Kibana is started and enabled at boot
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy Kibana configuration
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: Restart Kibana
